spring.application.name=demo
nephren.raven.apiclient.packages=com.example.demo.client
nephren.raven.apiclient.configs.ravenApiClient.url=http://localhost:8000
nephren.raven.apiclient.configs.ravenApiClient.connect-timeout=2s
nephren.raven.apiclient.configs.ravenApiClient.read-timeout=2s
nephren.raven.apiclient.configs.ravenApiClient.write-timeout=2s
#spring.mvc.log-request-details=true
#logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=TRACE
#logging.level.reactor.netty.http.client=DEBUG
#spring.output.ansi.enabled=ALWAYS
