spring.application.name=demo
blibli.backend.apiclient.packages=com.example.demo.client
blibli.backend.apiclient.configs.apiClient.url=http://localhost:8000
blibli.backend.apiclient.configs.apiClient.connect-timeout=2s
blibli.backend.apiclient.configs.apiClient.read-timeout=2s
blibli.backend.apiclient.configs.apiClient.write-timeout=2s
blibli.backend.apiclient.configs.apiClient.headers.Accept=application/json
server.port=8000
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=TRACE
