spring.application.name=demo
nephren.raven.apiclient.packages=com.example.demo.client
nephren.raven.apiclient.configs.apiClient.url=http://localhost:8000
nephren.raven.apiclient.configs.apiClient.connect-timeout=2s
nephren.raven.apiclient.configs.apiClient.read-timeout=2s
nephren.raven.apiclient.configs.apiClient.write-timeout=2s
nephren.raven.apiclient.configs.apiClient.headers.Accept=application/json